name: Build Windows Executable

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.2'
        target: 'desktop'
        arch: 'win64_mingw'

    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles"
        cmake --build . --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MiApp-Windows
        path: build/*.exe