name: Build Windows Executable

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.2'
        target: 'desktop'
        # Usamos el compilador nativo de Windows para evitar choques
        arch: 'win64_msvc2022_64'

    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake .. 
        cmake --build . --config Release

    - name: Deploy Qt Dependencies
      run: |
        mkdir Phoca-Windows
        # Con MSVC, el ejecutable se guarda en la carpeta Release
        Copy-Item build\Release\*.exe Phoca-Windows\
        windeployqt Phoca-Windows\

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Phoca-Windows-Portable
        path: Phoca-Windows\
